### ISSUE TITLE
Panic when reading an invalid transaction file

### ISSUE THREAD

**Issue by Kerollmops** [njaard/sonnerie#18] opened 2022-06-26 14:04 UTC
Hey,

I am currently using sonnerie to collect textual data by using the `CreateTx::new` and `CreateTx::commit` API.
I have set up two crontab rules to do a minor compaction every 10min and a major one every day.

Unfortunately, I just checked the database this morning and no compaction was performed for 12h or something. It was due to the reading programs crashing with the following backtrace. I found out that it was due to a transaction file I just uploaded, and this transaction file looks very big so it must be the output of compaction. This bug is also present in the main branch.

[tx.16fc0c7069ca48ed.zip](https://github.com/njaard/sonnerie/files/8986757/tx.16fc0c7069ca48ed.zip)

<details>
  <summary>Click to expand the backtrace</summary>

```
thread 'main' panicked at 'range end index 4 out of range for slice of length 0', library/core/src/slice/index.rs:73:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/slice/index.rs:73:5
   3: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
   4: core::intrinsics::const_eval_select
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/intrinsics.rs:2361:5
   5: core::slice::index::slice_end_index_len_fail
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/slice/index.rs:67:9
   6: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/slice/index.rs:303:13
   7: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/slice/index.rs:18:9
   8: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/vec/mod.rs:2533:9
   9: sonnerie::segment_reader::SegmentReader::open
             at ./src/segment_reader.rs:39:42
  10: sonnerie::key_reader::Reader::new
             at ./src/key_reader.rs:29:9
  11: sonnerie::database_reader::DatabaseReader::new_opts
             at ./src/database_reader.rs:100:12
  12: sonnerie::database_reader::DatabaseReader::new
             at ./src/database_reader.rs:36:3
  13: sonnerie::main
             at ./src/main.rs:209:12
  14: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

I am not sure but it looks like [the `decode_into_with_unescaping` function](https://github.com/njaard/sonnerie/blob/19fd43142ae1c9bb5ad81d6ecc89bfa94e5dc1c9/src/segment_reader.rs#L29) isn't filling the buffer correctly which makes the program crash as it is trying to read it with the `[..]` panicking syntax.

Also, I would like to say thank you because the fact that we can't read (and compact) the database isn't impacting the write operations. This is very cool as we can simply remove the broken transaction to make the system work again 🎉

**Comment by njaard** [comment] 2022-06-26 15:46
Like your pull request indicates, the file starts with a whole bunch of empty segments, and I don't understand how they got there. I will investigate.

I don't personally use the string value feature, so it's not entirely surprising that it's the least tested.

Please allow me a day or two to investigate the root cause, because files with empty segments should not be generated.

Another fix for this is to just edit your transaction file and remove all of the empty segments.

**Comment by Kerollmops** [comment] 2022-06-26 16:44
Thank you for the time you'll take on this bug, I just added a new commit to my PR and a few sentences in the description of it. With this new commit, I am able to convert and read the data with the current sonnerie binary (no more empty segments).

**Comment by njaard** [comment] 2022-06-26 18:55
It looks as though you're doing something sort of like this:

```
add_record("chowh1", "s", b"data that is not quite properly encoded")
```

The data you pass to `add_record` when you are using a string format must be in the form:
* 8 bytes of timestamp
* a varint representing the length of the string
* the string

I think it's possible that when you called `add_record`, you didn't encode the data properly and `add_record` didn't store it properly. Sonnerie should have returned an error in this condition while trying to write the recor, but I would still like to verify that this is what's happening in your code.

**Comment by Kerollmops** [comment] 2022-06-26 19:06
Here is what I am doing in my code base. BTW it would be maybe a good thing to mention the `escape_string`
 crate in sonnerie 😄 I had a bad time trying to encode strings on my own.

```rust
struct TimedUserMessage {
    server_timestamp: DateTime<Utc>,
    channel_login: String,
    sender_login: String,
    message_text: String,
}

let format = parse_row_format("ss");

fn prepare_and_write_messages(
    path: &Path,
    mut messages: Vec<TimedUserMessage>,
    row_format: &Box<dyn RowFormat>,
    protocol_buffer: &mut Vec<u8>,
) -> Result<Vec<TimedUserMessage>, WriteFailure> {
    let mut txn = CreateTx::new(path)?;

    messages.sort_unstable();
    messages.dedup_by_key(|msg| msg.server_timestamp);

    for mut message in messages.drain(..) {
        let mut text = mem::take(&mut message.sender_login);
        text.push(' ');
        text.push_str(&escape_string::escape(&message.message_text));

        protocol_buffer.clear();
        let ts = message.server_timestamp.timestamp_nanos() as u64;
        row_format.to_stored_format(ts, &text, protocol_buffer).unwrap();
        txn.add_record(&message.channel_login, "ss", protocol_buffer)?;
    }

    txn.commit().map_err(Into::into).map(|_| messages)
}
```

**Comment by njaard** [comment] 2022-06-27 17:41
Hi @Kerollmops , I have just published version 0.7.1 with a fix for your problem! I didn't apply the part where it's able to read those broken segments, because then it would mask the root problem.

Thanks a lot for your patience and helpful diagnosis information!

I hope to have a high-level api to replace `add_record` soon which will negate the inconvenience of the `escape_string` problem!

**Closed by njaard** 2022-06-27 17:41 UTC

**Comment by njaard** [comment] 2022-06-29 00:42
Hi @Kerollmops, I have a version of Sonnerie with a [high-level API](https://github.com/njaard/sonnerie/issues/11) that should make encoding data a little easier, it's in the [high-level-write](https://github.com/njaard/sonnerie/tree/high-level-write) branch.

The inside of your for-loop would look like this (and no more boilerplate!):

```
txn.add_record(
    &message.channel_login,
    message.server_timestamp,
    record("ss", &message.sender_login, &message.message_text
)?;
```
I hope you can give the branch a look at give me your feedback.

**Comment by Kerollmops** [comment] 2022-07-01 12:55
Hey @njaard,

Thank you very much for this improved API, I just tried it out and it works great, however, would be great to make the `BuildingRecord` and `RecordBuilderEnd` types public as we can't see their documentation right now.

Also, I couldn't directly use `&message.sender_login` as those are `String`s, Rust was complaining so I needed to switch to `message.sender_login.as_str()`.
